{
 "title": "Backtesting",
 "time": { "from": "2024-12-31T17:00:00.000Z", "to": "2025-05-31T17:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "backtest_id",
    "label": "Backtest ID",
    "query": "from(bucket: \"trading\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"backtest\")\n  |> filter(fn: (r) => r._field == \"backtest_id\")\n  |> keep(columns: [\"_value\"])\n  |> group()\n  |> distinct(column: \"_value\")\n  |> sort(columns: [\"_value\"])\n  |> map(fn: (r) => ({_text: string(v: r._value), _value: string(v: r._value)}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Drawdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"trading\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backtest\")\n  |> filter(fn: (r) => r[\"_field\"] == \"drawdown\" or r[\"_field\"] == \"backtest_id\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => exists r.backtest_id and exists r.drawdown)\n  |> filter(fn: (r) => r.backtest_id == \"${backtest_id}\")\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r.drawdown), _field: \"drawdown\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: max)"
    }
   ]
  },
  {
   "title": "Equity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"trading\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backtest\")\n  |> filter(fn: (r) => r[\"_field\"] == \"equity\" or r[\"_field\"] == \"backtest_id\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => exists r.backtest_id and exists r.equity)\n  |> filter(fn: (r) => r.backtest_id == \"${backtest_id}\")\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r.equity), _field: \"equity\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: max)"
    }
   ]
  },
  {
   "title": "Sharpe Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"trading\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backtest\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sharpe_ratio\" or r[\"_field\"] == \"backtest_id\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => exists r.backtest_id and exists r.sharpe_ratio)\n  |> filter(fn: (r) => r.backtest_id == \"${backtest_id}\")\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r.sharpe_ratio), _field: \"sharpe_ratio\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: min)"
    }
   ]
  }
 ]
}