instrument: SOL-USDT-SWAP

backtest:
  dataset: SOL-TRADE-OKX
  # depth:
  #   hour: 5
  #   minute: 30

crossma:
  short_length: 1000
  long_length: 50000

drawdown:
  window: 100000
  threshold_scale_map:
    0.0: 1.0
    0.01: 0.2
    0.05: 0.01
