instrument: SOL-USDT-SWAP

depth:
  hour: 5
  minute: 30

crossma:
  short_length: 50
  long_length: 100

drawdown:
  window: 1440
  threshold_scale_map:
    0.0: 1.0
    0.02: 0.2
    0.05: 0.01
