instrument: SOL-USDT-SWAP
strategy: drawdown_meanrev

backtest:
  dataset: SOL-TRADE-OKX
  fee_rate: 0.0005
  initial_equity: 1000.0
  # depth:
  #   hour: 5
  #   minute: 30

crossma:
  short_length: 200
  long_length: 1000

drawdown:
  window: 100000
  threshold_scale_map:
    0.0: 1.0
    0.01: 0.1
    0.05: 0.01

meanrev:
  lookback: 50000
  entry_threshold: 2.0
  exit_threshold: 0.5
